server:
  port: 8081
spring:
  data:
    mongodb:
      port: 27017
      auto-index-creation: 'true'
      database: BankAccountdb
      host: localhost
  application:
    name: ms-account
  config:
    import: optional:configserver:http://config-server:8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
      instance-id: ${spring.application.name}:${random.uuid}